### ISSUE TITLE
cjs-module-analyzer doesn't find requires if they're not top-level

### ISSUE THREAD

**Issue by naugtur** [endojs/endo#1083]
```js
const { requires } = analyzeCommonJS(`
  mime(require('./types/standard'), require('./types/other'));
  `);
```

`requires` is an empty array.

Works fine if `require` call statements are not arguments to a function

Attempted fix:  
https://github.com/endojs/endo/commit/2703569cd663040c7cb1f3efb7b786ed1d6249d6

The change causes any `require()` call to produce a `requires` entry, which may lead to 
```
 Cannot find file for internal module "./niematakiegonumeru" (with candidates "./niematakiegonumeru", "./niematakiegonumeru.js", "./niematakiegonumeru/index.js") in package file:///...
 ```
 Which in turn could be solved with a change here:  https://github.com/endojs/endo/blob/a7b42ae2388b232f7daa099495ba11f385010fd1/packages/compartment-mapper/src/import-hook.js#L160-L175 
Instead of erroring out, returning a dummy static module record that throws the error when execute is called could work. That way it'd emulate cjs more closely and not fail if the `require` reference was not the actual require.

**Comment by kriskowal** [comment]
Yeah, the approach of returning a dummy static module record is used elsewhere here (for exit modules) and I’ve used the trick for CommonJS bundlers in the past. This is not a problem for ESM loaders in general and I hesitate to make errors occur later in ESM when they don’t have to. But, I don’t have any idea how to fix this for CJS without affecting ESM.

I established a precedent, unfortunately, for compromising ESM to get CJS to work: the extension and + `/index.js` search path should only apply to CommonJS, but since it’s a behavior of the loader and not part of the language-specific parser, I appeased CommonJS. Consequently, Endo like `node -r esm`, will encourage use patterns that aren’t portable back to Node.js.

So, given the design tensions as they stand, I’m okay with proceeding in the direction you suggest, but we should think of the minimum complication we can add to the compartment mapper to avoid both of these compromises, that is, restrict ESM to importing exact locations instead of searching but allow CommonJS to search, and allow CommonJS to have a conditional require that fails at evaluation time instead of load time, without deferring a missing ESM module error to runtime. So far, I can’t think of a way to do that.

**Comment by naugtur** [comment]
I added postponing errors to import-hook and started looking into decoupling esm and cjs there.

Parsing needs to differ between esm and cjs, so it's provided as an argument. 
Meanwhile figuring out local paths is following the cjs logic, as you said. 

All the differences could come in from` mapParsers` (with a name change ofc) where instead of a `parse` we'd get `{ parse, generateCandidates, errorReporter }`

`mapParsers` is aware of cjs already and all that awareness could potentially be encapsulated there.

**Comment by shrinktofit** [comment]
#1090 does not capture the following require:

```js
import { analyzeCommonJS } from '@endo/cjs-module-analyzer';
const info = analyzeCommonJS(`
(function(){
    require('crypto');
})();
`);
console.log(JSON.stringify(info, undefined, 2)); // All empty arrays
```

**Comment by naugtur** [comment]
@shrinktofit 
I've added a test for that and it passes
```js
test('Identify require calls in clojures', t => {
  const { requires } = analyzeCommonJS(`
    (function(){
      require('crypto');
    })();
  `);
  t.is(requires.length, 1);
});

```

Are you sure you're using a version that's up to date?

**Comment by shrinktofit** [comment]
> @shrinktofit I've added a test for that and it passes
> 
> ```js
> test('Identify require calls in clojures', t => {
>   const { requires } = analyzeCommonJS(`
>     (function(){
>       require('crypto');
>     })();
>   `);
>   t.is(requires.length, 1);
> });
> ```
> 
> Are you sure you're using a version that's up to date?

Well it may be my fault ..
