### ISSUE TITLE
When NPM?

### ISSUE THREAD

**Issue by gamedevsam** [endojs/endo#1128]
I want to use `lockdown` to increase security of my node programs (eliminate prototype pollution types of issues). In addition, harden is just a useful utility that could be beneficial to anyone.

Any plans to release harden / lockdown as their own separate packages?

**Comment by gamedevsam** [comment]
Nevermind, the repo / package name mismatch caused brief confusion: https://www.npmjs.com/package/ses

**Comment by kriskowal** [comment]
Thanks @gamedevsam. We did originally publish a separate package, but we were convinced to consolidate `lockdown()` and `harden()` because calling `harden` on just about any object obviates the possibility of later successfully calling `lockdown()`, since the latter step requires the intrinsics to be repairable. We’ve since changed `lockdown` such that it reveals `harden` only when it’s safe to use.
