### ISSUE TITLE
Some parsers in our toolchain choke on "?."

### ISSUE THREAD

**Issue by erights** [endojs/endo#1514]
See https://github.com/endojs/endo/pull/1513#issuecomment-1473061658

Separately, @kriskowal sent me 

> The length undefined error means minify failed and returned a result struct with error info instead of the code. Probably a syntax error, probably a stale version of the minifier.

That was the clue I needed. The new code in this PR contained a "?.". Once refactored to avoid any such newer syntax, CI is much happier.

**Comment by turadg** [comment]
Terser didn't support optional chaining until 5.2: https://github.com/terser/terser/blob/master/CHANGELOG.md#v520

The repo currently imports 4.8.1, the latest without hitting the breaking changes of 5.0: https://github.com/terser/terser/blob/master/CHANGELOG.md#v500-beta0

**Comment by michaelfig** [comment]
Notable culprits:
  - Node 12 in the platform-compatibility-test,
  - webpack 4.46.0 in the integration-test

**Comment by kriskowal** [comment]
We have since added a lint rule forbidding optional chaining. We discovered that `esm` in the Agoric SDK testnet load generator used a `node -r esm` deploy script and failed with optional chaining.

Closing this issue as addressed, though we hope to obviate the need and drop support for some of these tests and tools.
