### ISSUE TITLE
performance note: Node's Promise.resolve is oddly slow

### ISSUE THREAD

**Issue by erights** [endojs/endo#1637]
In doing some exploratory speed experiments while running on Node, I was surprised at how much time `Promise.resolve` takes ***per call***. The following screenshot, from a debug session on an unrelated PR, is a big clue.

![image](https://github.com/endojs/endo/assets/273868/b38e0509-dac7-46c9-be2b-8adf84a78486)

**Comment by mhofman** [comment]
@erights you cannot use a trace captured if the debugger was attached to get representative profile of promise logic in node. The reason is that attaching a debugger triggers the async_hook logic, including our patch to fix the incompatibility with frozen promises. That stuff is all very expensive.

An alternative is to [programmatically start a profile sessions using the v8 API](https://nodejs.org/api/v8.html#new-v8gcprofiler) (Node 18+) or use the [command line arguments](https://nodejs.org/api/cli.html#--cpu-prof)

**Comment by erights** [comment]
That explains it, Thanks! Closing.
