### ISSUE TITLE
Pet Daemon: Prototype of remote connections between daemons using Tailscale, November 2023

### ISSUE THREAD

**Issue by aj-agoric** [endojs/endo#1828]
## What is the Problem Being Solved?
Pet Daemon: Prototype of remote connections between daemons using Tor, November 2023
From [MetaMask Requirements](https://docs.google.com/document/d/16u_JpaMNc-5Xp4l0fQn3OPAWFUIX-5gxtPWuIu6-fQ0/edit)

**Comment by aj-agoric** [comment]
Triaged in today's meeting and decided this is the best guess for now

**Comment by kriskowal** [comment]
@danfinlay @kumavis @rekmarks I’ve revised this issue to reflect that we achieved pet daemon connectivity using Tailscale instead of Tor for the purposes of our prototype and closing. This ends the prototype spike and I believe adequately closes out our planned deliverables for the 2023 grant, with your blessing. See also https://github.com/endojs/endo/issues/1829
