### ISSUE TITLE
Rethink Global Lexical Environment support

### ISSUE THREAD

**Issue by erights** [endojs/endo#19]
We had been thinking that the endowments mechanism could be used as the evaluator's emulation of the global lexical environment. However, we were also thinking that the endowments object not be extensible. Unfortunately, the ES std semantics requires the global lexical scope to be extensible under script evaluation.

No decision now. Noting that we need to revisit this.

**Comment by kriskowal** [comment]
We’ve since introduced a `globalLexicals` option, which gives us an immutable non-enumerable scope to introduce instrumentation that can only be reached by name and consequently hidden from client code with a censoring or renaming transform.

That feature does not address the need for an evaluation mode where a lexical scope in which `const` and `let` declarations are preserved between calls to `evaluate`, as is necessary to faithfully implement a REPL. I’ve added this issue to the “Reasses” column of our work board.

**Comment by kriskowal** [comment]
When we add Compartment `evaluate` modes for “sloppy” evaluation or evaluation of “global code”, we will need to make the global lexicals mutable, e.g., when one calls `compartment.evaluate("const foo = 10")`.

**Comment by erights** [comment]
@kriskowal I think we settled this on a semantics we are happy to commit to. I assigned the two of us. If you agree this is settled, please close this.
