### ISSUE TITLE
Chrome devtools likely to be unpleasant on our repaired properties

### ISSUE THREAD

**Issue by erights** [endojs/endo#281]
At https://bugs.chromium.org/p/v8/issues/detail?id=10472 Bloomberg filed an issue about the Chrome debugger presenting a confusing display as a result of their workaround to the override bug. Their override seems to be the same: https://github.com/Agoric/SES-shim/blob/master/packages/ses/src/enable-property-overrides.js , so we are likely to experience the same unpleasantness. Not verified.

Attn @robpalme

**Comment by erights** [comment]
Issue moved to https://bugs.chromium.org/p/chromium/issues/detail?id=1076820

**Comment by kriskowal** [comment]
We have since verified that we experience the same unpleasantness and provide a lot of nobs for controlling the extent we mitigate property override. However, short of fixing property override, no further action from us will advance this issue. Closing for now in favor of more specific action https://github.com/endojs/endo/issues/1912
