### ISSUE TITLE
Deprecate `@agoric/harden` and `@agoric/make-hardener`

### ISSUE THREAD

**Issue by jfparadis** [endojs/endo#41]
[edit @kriskowal 2020-08-12]

- [x] Deprecate `@agoric/harden` by publishing a next-breaking version with only a README notifying the public of the deprecation and recommended alternatives, also noting that version 0.0.4 was the last coherent release if it remains necessary.
- [x] Subsume `@agoric/make-hardener` into `ses` and deprecate the former. Since there’s no sensible use of `make-hardener` without SES, it should not be possible to use it as an external dependency.

---

[original @jfparadis 2020-02-20]

I'm capturing and trying to summarize discussions around  `harden` with @warner :

> Publising to npm a package named `harden` raises concerns, because when used outside SES, someone could make the wrong assumptions about `harden` and security.

Specifically, invoking `harden` outside of SES does not throw even if `Object.prototype` is not frozen. This is because `Object.prototype` is in the pre-populated fringe set.

The concern is that `@agoric/harden` appears to provides safety, which it does when invoked under SES, but when used outside of SES, it doesn't provide the same level of safety.

**Comment by kriskowal** [comment]
Based on this observation, we no longer support the `@agoric/harden` and `@agoric/make-hardener` packages. Splitting a light version of `ses/lockdown` allows us to use the `harden` global variable introduced by SES in every environment. Our stance now is that there is no coherent formulation of `harden` before `lockdown`. If an application wishes to optionally harden, they must bring their own no-op `harden` into global scope.

The remaining work toward this consensus is:

- Deprecate `@agoric/harden` by publishing a next-breaking version with only a README notifying the public of the deprecation and recommended alternatives, also noting that version 0.0.4 was the last coherent release if it remains necessary.
- Subsume `@agoric/make-hardener` into `ses` and deprecate the former. Since there’s no sensible use of `make-hardener` without SES, it should not be possible to use it as an external dependency.

Updating the description to match.

**Comment by erights** [comment]
@kriskowal done now? Close?

**Comment by kriskowal** [comment]
Yes, 3ef842f4b accomplished this a month ago. Thanks.
