### ISSUE TITLE
Browser: removed intrinsics

### ISSUE THREAD

**Issue by michaelfig** [endojs/endo#464]
I get these messages when running SES in the browser (Brave).  Are these methods intended to be whitelisted?

```
whitelist-intrinsics.js:233: Removing intrinsics.Promise.any
whitelist-intrinsics.js:233: Removing intrinsics.%StringPrototype%.replaceAll
```

**Comment by erights** [comment]
`replaceAll` done.

`Promise.any` is in the whilelist as a false, which will make this message go away. The message is to tell us about surprises we should be aware of. A false in the whitelist, like an absence, causes the property to be removed. But false indicates that we weren't surprised to see it. So closing this one.

There remains https://github.com/Agoric/SES-shim/issues/550 for enabling `Promise.any` together with `AggregateError`. We cannot enable `Promise.any` until we enable `AggregateError`. The latter isn't trivial because it doesn't follow the normal error constructor pattern.

**Comment by erights** [comment]
Sorry, I'm reopening until I see that these are gone. If you see that these are gone first, please close this.

**Comment by AidenRourke** [comment]
I'm seeing

`Removing intrinsics.Array.@wry/context:Slot`

In my browser all of a sudden followed by the error

`failed to delete intrinsics.Array.@wry/context:Slot (TypeError#1)`

**Comment by erights** [comment]
I checked recently. Closing.
