### ISSUE TITLE
XS Compartment constructor with module loader hooks

### ISSUE THREAD

**Issue by dckc** [endojs/endo#536]
@kriskowal my current solution in agoric-sdk is [endo-load.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/src/endo-load.js), called from [start-xs.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/start-xs.js)

It consumes the output of [findmods.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/tools/findmods.js), which runs under node.js and uses [filing-cabinet](https://www.npmjs.com/package/filing-cabinet) to walk the tree of module dependencies.

As I think I mentioned, in contrast to `xsnap`, where all .js scripts and modules are loaded / parsed at runtime, `start-xs.js` and `endo-load.js` start in a world where all the `StaticModuleRecord`s are in compiled bytecodes. See [Makefile](https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/Makefile) for details.

originally raised as: https://github.com/Agoric/agoric-sdk/issues/57

**Comment by dckc** [comment]
oh... the `endo-types` branch might be easier to read, @kriskowal :
https://github.com/dckc/agoric-sdk/blob/endo-types/packages/xs-vat-worker/src/endo-load.js
https://github.com/dckc/agoric-sdk/blob/endo-types/packages/xs-vat-worker/src/endo-types.d.ts

**Comment by dckc** [comment]
Now that `findmods.js` is obsolete in favor of xsnap and rollup, let's use this to represent `dynamicModuleLoading` and such as discussed in https://github.com/Agoric/agoric-sdk/issues/2107 .

**Comment by dckc** [comment]
@kriskowal here's hoping you can get to this soonish...

**Comment by kriskowal** [comment]
This might be ready-to-try. It needs `compartment-mapper` and `ses-shim` (full stack, including babel) running in XS.

**Comment by dckc** [comment]
Including babel? I thought the purpose of this was to avoid babel. I wonder where I got confused.

**Comment by kriskowal** [comment]
Oh, no. I am confused because you put it on my plate. If it’s on my plate, that implies we’d be doing compartments with the ses-shim. If we’re doing “XS Compartment constructor with module loader hooks”, we’re writing C.

**Comment by dckc** [comment]
yes, I'm kinda muddled in my thinking. Hm.

**Comment by erights** [comment]
My understanding is that the next step is to use the builtin XS `Compartment` only as an evaluator that can replace the 8 magic lines of code. We still need to build @kriskowal 's `Compartment on top of that in order to handle modules the way we need.

**Comment by erights** [comment]
When removing the 8 magic lines of code, we need to carefully examine which if any safety checks we're removing. The builtin XS `Compartment` will still do something not to our liking with dynamic `import(...)` expression, so we'll still need to prohibit it. We should also continue to prohibit html comments, but this is arguable. We can *almost* drop the prohibition on direct eval, because the builtin XS `Compartment` implements direct eval correctly. However, there's no way to do so while still enforcing these very prohibitions.

**Comment by kriskowal** [comment]
I think this issue largely falls under https://github.com/endojs/endo/issues/400, surfacing native XS Compartment when running SES on XSnap. That in turn also covers work Moddable has already done to support dynamic module loading. All that remains is some hypothetical work to make compartment mapper useful for generating XS native manifests, but I don’t intend to track that since it’s not well-motivated. I’m closing this in favor of ongoing tracking in #400. Please reöpen if this represents some other work.
