### ISSUE TITLE
cannot coerce detailsToken to string

### ISSUE THREAD

**Issue by dckc** [endojs/endo#729]
We construct `detailsToken` as follows:

https://github.com/endojs/endo/blob/fb06d7d5fc0cef5725e1ca369f2adce765924b4a/packages/ses/src/error/assert.js#L72

and similarly on line 92.

Then in `assert.note`, we attempt to stringify it:

```
  if (hiddenDetails === undefined) {
    throw new Error(`unrecognized details ${detailsNote}`);
  }
```

On XS, this throws `cannot coerce object to string`. On node, likewise:

```
> `${{__proto__: null}}`
Thrown:
TypeError: Cannot convert object to primitive value
```

It seems error-prone to try to prevent stringifying `detailsToken`, so I suggest adding `toString()` methods.

context:

The moddable folks pointed this out in the course of debugging https://github.com/Agoric/agoric-sdk/issues/3039; it was triggered in [trackTurns](https://github.com/Agoric/agoric-sdk/blob/master/packages/eventual-send/src/track-turns.js#L41):

```
  if (hiddenPriorError !== undefined) {
    assert.note(sendingError, X`Caused by: ${hiddenPriorError}`);
  }
```

**Comment by erights** [comment]
@dckc I agree with your recommendation and will do that. But reading the code, I am confused how this arose. The `detailsToken` constructed near lines 72 and 92 are both followed by 
```js
hiddenDetailsMap.set(detailsToken, { template, args });
```
We never remove it from that weakmap or store anything else in there. The line immediate prior to both occurrences of the test you show above is
```js
  const hiddenDetails = hiddenDetailsMap.get(optDetails);
```
Thus, for the `detailsToken`s made near lines 72 and 92, *if we are using the same instance of the assert module* and thus the same weakmap, I don't see how `hiddenDetails` can ever be `undefined`.

If we are instantiating the `assert` module twice, so that one doesn't recognize the `detailsToken` generated by the other, that itself would be a bad problem we need to fix. Can you help me reproduce this?

**Comment by dckc** [comment]
> @dckc ... We never remove it from that weakmap ... I don't see how `hiddenDetails` can ever be `undefined`. ... Can you help me reproduce this?

I'm not confident that I can, on node; as I say, arose in the context of https://github.com/Agoric/agoric-sdk/issues/3039 , which has since been diagnosed as a GC bug in XS that resulted in things getting dropped from `WeakMap`s.
