### ISSUE TITLE
SES module emulation of CommonJS named exports

### ISSUE THREAD

**Issue by kriskowal** [endojs/endo#744]
Considering the following case:

```js
// exports.cjs
exports.name = 1;
```

```js
// module-exports.cjs
module.default = 1;
```

```js
// imports.mjs (or imports.js for node -r esm imports.js)
import exportsName from './exports.cjs';
import * as exportsNameStar from './exports.cjs';
import moduleExports from './module-exports.cjs';
import * as moduleExportsStar from './module-exports.cjs';
console.log({
  exportsName,
  exportsNameStar,
  moduleExports,
  moduleExportsStar,
});
```

Node.js 12:

```
(node:10205) ExperimentalWarning: The ESM module loader is experimental.
{
  exportsName: { name: 1 },
  exportsNameStar: [Module] { default: { name: 1 } },
  moduleExports: 1,
  moduleExportsStar: [Module] { default: 1 }
}
```

Node.js 14:

```
{
  exportsName: { name: 1 },
  exportsNameStar: [Module] { default: { name: 1 }, name: 1 },
  moduleExports: 1,
  moduleExportsStar: [Module] { default: 1 }
}
```

Node.js 16:

```
{
  exportsName: { name: 1 },
  exportsNameStar: [Module: null prototype] { default: { name: 1 }, name: 1 },
  moduleExports: 1,
  moduleExportsStar: [Module: null prototype] { default: 1 }
}
```

Node.js 16 `node -r esm`

```
{
  exportsName: { name: 1 },
  exportsNameStar: [Object: null prototype] [Module] { default: { name: 1 }, name: 1 },
  moduleExports: 1,
  moduleExportsStar: [Object: null prototype] [Module] { default: 1 }
}
```

SES does not yet implement all of these cases and should provide some consistent story, perhaps even a migration path from Node.js 14 to 16 semantics on a per-package basis.

**Comment by erights** [comment]
FWIW, here were my guesses after reading the question and before the answers. Frighteningly wrong. However... (next message)
```js
exportsName: undefined,
exportsNameStar: { name: 1 },
moduleExports: 1,
moduleExportsStar: { default: 1 } // or {}
```

**Comment by erights** [comment]
AFAICT, for the module-exports.cjs examples, your outputs are not possible given the stated input. Did you mean
```
// module-exports.cjs
module.default = 'name';
```

**Comment by kriskowal** [comment]
> AFAICT, for the module-exports.cjs examples, your outputs are not possible given the stated input. Did you mean
> 
> ```
> // module-exports.cjs
> module.default = 'name';
> ```
> 
> ?

I spotted the inconsistency and reran the suite and updated the description so the results are consistent with a snapshot. It bears mentioning that you cannot name an import `exports` in RESM because it conflicts with the CommonJS `exports` in the same scope, showing a seam in the emulation like `__filename` and `__dirname`.

**Comment by kriskowal** [comment]
I was surprised that the consensus seems to be settling on duplication for `exportsNameStar`.

```
  exportsNameStar: { default: { name: 1 }, name: 1}
```

**Comment by erights** [comment]
What does the square bracket notation above mean? Such as `[Object: null prototype] [Module]`

**Comment by kriskowal** [comment]
The output above is verbatim from the Node.js console and I don’t know how to interpret that.

:warning: Don’t get drawn into the nerd-snipe. I posted the issue so I could clear it out of my working copy and not think about it for a long time. 😉

**Comment by naugtur** [comment]
Aaaand we're back.

The current behavior, as of https://github.com/endojs/endo/commit/3159165d6c204358cf65cf856db85134dc348c21 is matching node 16 as evident from (potentially too many) tests included. It's even a little bit more generous in promoting fields to named exports, because node limits that only to fields that the cjs lexer managed to identify (which is scary, because the changes you need to make to loose a named export can be as little as updating prettier and running it, but I digress)

The change from node 12 to node 14 is additive (named export promoted from default to root namespace) and there doesn't seem to be a lot of complaints about that. Node 12 EOL is 2022-04-30. Let's not talk about it further maybe? 

The change from node 14 to node 16 is more of a breaking change - you can no longer reach methods from Object.prototype from the imported reference. On the other hand - node rolled it out happily, without backlash. Why do we care?

Asking @kriskowal to approve closing this as fixed by #1074

**Comment by kriskowal** [comment]
Victory!

**Comment by naugtur** [comment]
BTW, I couldn't reproduce the differences in fields between node 12 and 14. Looks like later versions fixed it.
