### ISSUE TITLE
Peer-review make-hardener code

### ISSUE THREAD

**Issue by andrey-kuprianov** [endojs/endo#746]
_Surfaced from @informalsystems Agoric Audit of endojs/endo hash f7dcf050ef0fd839ab6500b938791740c9bc702b_

The [make-hardener](https://github.com/endojs/endo/tree/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener) package seems to be the cornerstone on which the security of SES and thus of the SwingSet lies; therefore we have taken some effort to inspect it. We have also created some manual tests to boost our confidence in its correctness.

While no major issues are found, here are a few points from that inspection:

- In [this comment](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L103-L105) it is said about using `hasOwnProperty` to ensure about `value` presence; but the function is not actually used in the code
- The [paths variable](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L47) is tracked while hardening, but is never used
- Similarly, the [hardened variable](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L37) doesn't seem to be used in a reasonable fashion, besides being updated in the very last step in [commit](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L136), and in [this condition](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L65). The last one can actually be dangerous if some later code changes add smth. to `hardened`: this may lead to some parts of the object graph being silently ignored.
- The [enqueue function](https://github.com/endojs/endo/blob/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener/src/main.js#L55-L72) contains several conditionals with two of them silently returning. While this may be fine now, there may be conditions for which this doesn't account, or conditions that may change for JavaScript later. It is recommended to rework this conditionals into nested ones, with `if`/`else` branches, to make sure that whatever is not processed (frozen), throws an exception.

**Recommendation**: do a peer review of [make-hardener](https://github.com/endojs/endo/tree/f7dcf050ef0fd839ab6500b938791740c9bc702b/packages/make-hardener) and rework the code to make it bullet-proof.

**Comment by Tartuffo** [comment]
@kriskowal Can you look at this and decide if it needs MN-1 work.

**Comment by kriskowal** [comment]
As of 66189beb67a3c89de3ad2c00a8196f9cc214e044

1. `makeHardener` has since been altered to make use of `hasOwnProperty` per the comment in question.
2. `paths` are used to raise useful errors if hardening fails
3. The `hardened` variable makes `harden` transactional, so if some transitive node in the hardened reference graph causes `harden` to throw an exception, the partial state is discarded and a subsequent harden will review these objects.
4. `enqueue` is a no-op for primitives and for objects that have already successfully been transitively frozen in a prior hardening. These cases must not throw exceptions.

Based on this feedback, we did a peer review of `makeHardener` with the MetaMask team https://agoric.com/blog/technology/metamask-agoric-hardened-js-security-review/ and collectively received a better understanding of this function and also found no defects.

I believe we have satisfied this issue sufficiently, particularly for use in Agoric Mainnet 1, and welcome feedback to the contrary.

Thank you @andrey-kuprianov!
