### ISSUE TITLE
String.prototype.at - Stage 3 proposal

### ISSUE THREAD

**Issue by dckc** [endojs/endo#854]
@warner notes:
> I'm seeing a bunch of `Removing intrinsics.%StringPrototype%.at` printed during tests

Array.prototype.at, String.prototype.at and TypedArray.prototype.at are implemented in XS around https://github.com/Moddable-OpenSource/moddable/commit/e6391305217190cd7da7f706eb3dfaad6275cee5#diff-a159eaf43ba28f0de1e182d76fa2fe9a89fd1023fec920b80e5ba10824dcaf9d

I gather it's a Stage 3 proposal. At what stage do globals belong in the ses whitelist?

**Comment by erights** [comment]
> I gather it's a Stage 3 proposal. At what stage do globals belong in the ses whitelist?

Stage 3. The other missing ones off the top of my head are 
   * `Promise.allSettled`, `AggregateError` pair. The first depends on the second.
   * `WeakMap` and `FinalizationRegistry`. The powerful globals are only on the start compartment, so no bit loss there. But `WeakMap.prototype` and `FinalizationRegistry.prototype` should be shared frozen primordials. Their absence is no big deal for Agoric, since they wouldn't be exposed to our user code anyway. But endo itself needs to be closer to JS in this regard.
