### ISSUE TITLE
Divergence when bundling `yarn install --production`

### ISSUE THREAD

**Issue by michaelfig** [endojs/endo#919]
I have checked that `dev` mode is disabled, but https://github.com/Agoric/agoric-sdk/tree/mfig-bundle-divergence/dev-vs-prod-bundle.sh reveals a difference between bundling in the two different `yarn install` situations.

TODO: More details

**Comment by kriskowal** [comment]
For reference, these are the differences in package layout between dev and prod: https://gist.github.com/kriskowal/dc51be6c08234a579f4eef33fd4a4bc8

The production steps:
```sh
yarn --frozen-lockfile
find . -name package.json | while read pkg; do jq -r --arg pkg "$(dirname $pkg)" '"\(.name)@\(.version) \($pkg)"' "$pkg"; done | sort > dev.list
yarn --frozen-lockfile --production
find . -name package.json | while read pkg; do jq -r --arg pkg "$(dirname $pkg)" '"\(.name)@\(.version) \($pkg)"' "$pkg"; done | sort > prod.list
diff dev.list prod.list
```

**Comment by kriskowal** [comment]
Also for reference, this is an example of the differences between dev and prod for one bundle in a zip file:

https://gist.github.com/kriskowal/f927e01a0cb9d9ab0b543543b39057f0

**Comment by kriskowal** [comment]
Arranging for bundles to be the same regardless of whether they are generated from files as laid out by yarn for development or production may only be possible by much more rigorous means.

Yarn and Npm are certainly allowed to put multiple copies of the same package [name, version] in the node_modules tree, but I think we can count on Yarn at least to use symbolic links to point to a single hard copy. Proceeding on that assumption.

I can remove the order numbers from the compartment names and merge any packages that have the same name and version. It should not be necessary to incorporate a consistent hash of the package, which is good because that would be expensive to obtain (the compartment mapper doesn’t have to read every file in a package, but a hasher would). We should at least verify that there is only one canonical location per name@version in a compartment map.

I’m no longer convinced that the solution to this problem is shaking out the unused edges in the compartment map.

**Comment by michaelfig** [comment]
> I can remove the order numbers from the compartment names and merge any packages that have the same name and version.

Is this what you are proposing as the solution?  That would be great!

Don't let me nerd-snipe you with this problem, though.  Only address what seems useful and addressable.

**Comment by kriskowal** [comment]
It’s an idea for a solution. I’m not sure that it will work.

**Comment by Tartuffo** [comment]
@michaelfig @kriskowal This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract
